#Spring properties
spring:
  aop:
   auto: true
   proxy-target-class: false
  messages:
    always-use-message-format: false
    basename: messages
  mvc:
    dispatch-trace-request: false
    dispatch-options-request: true
  couchbase:
    bucket:
      name: default
  thymeleaf:
    cache: true
#Security properties
security:
  oauth2:
    resource:
      prefer-token-info: true
      service-id: resource
      
#thymeleaf

   
   